start_date: 2024-01-01
end_date: 2024-02-01
currencies:
  -eur
  -usd
  -chf
output_folder : xxx
save_to_file: xxx
save_to_db: xxx
db_type: xxx
sqlite_database_file: xxx
db_host: xxx
db_port: xxx
db_name: xxx
db_user: xxx
db_pass: xxx